<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Duplicate English name</name>
   <tag></tag>
   <elementGuidId>312e0ed4-d28f-4158-81be-ca716c92c990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='English Name'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>98a1cd82-8d0c-4ea3-8a6c-001db7ce9723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r61:-form-item-message</value>
      <webElementGuid>30a61c8b-0bc5-4b45-8d88-988cacdbaccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium text-destructive</value>
      <webElementGuid>b606270a-fbc3-4da5-b05a-633ba95a1611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The name 'yretyy' in 'en' language is already taken.</value>
      <webElementGuid>8ff7579b-6ff5-455a-9350-8c367e0e6958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r61:-form-item-message&quot;)</value>
      <webElementGuid>9392b87a-87e5-40f2-ac7f-5271948fb38e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r61:-form-item-message']</value>
      <webElementGuid>c37f8a39-94bd-46e4-919c-af35931cc59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r3r:']/div[2]/form/div/div/p</value>
      <webElementGuid>9b4599fe-6d10-49f5-b682-8d662c5df345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English Name'])[1]/following::p[1]</value>
      <webElementGuid>4b5a7ce5-86a3-4244-bd09-0456e60a500d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Semester'])[1]/following::p[1]</value>
      <webElementGuid>e7582ad6-77fe-4b65-b9be-86e3593c1682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arabic Name'])[1]/preceding::p[1]</value>
      <webElementGuid>c21f3ca5-e5f5-40b3-a735-52107034093b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Academic Year'])[2]/preceding::p[1]</value>
      <webElementGuid>03677eb7-d896-473a-a83e-3f6812e50817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>b6ebbb00-bcd7-4bc5-9553-e832bea0138d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r61:-form-item-message' and (text() = concat(&quot;The name &quot; , &quot;'&quot; , &quot;yretyy&quot; , &quot;'&quot; , &quot; in &quot; , &quot;'&quot; , &quot;en&quot; , &quot;'&quot; , &quot; language is already taken.&quot;) or . = concat(&quot;The name &quot; , &quot;'&quot; , &quot;yretyy&quot; , &quot;'&quot; , &quot; in &quot; , &quot;'&quot; , &quot;en&quot; , &quot;'&quot; , &quot; language is already taken.&quot;))]</value>
      <webElementGuid>2a815421-abd4-418f-952e-9ef21f0af8cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
