<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arabic Name</name>
   <tag></tag>
   <elementGuidId>c52f50b6-cb72-4336-9dbc-085b16fd40d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'nameAR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f400d43-9c2f-4579-b67c-d7ee23173519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary-50 flex h-10 w-full rounded-md border bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring hover:bg-primary-20/20 transition-colors focus-within:bg-primary-20/20 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 peer-invalid:ring-red-600</value>
      <webElementGuid>7f437430-2e19-4f52-975c-48ac32244576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Subject name in arabic</value>
      <webElementGuid>f00b4284-c8b3-4f22-baae-2a7d5898b5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameAR</value>
      <webElementGuid>b2ba71b2-6203-40fd-b95f-a5b79d8875a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r4f:-form-item</value>
      <webElementGuid>9cbec02b-8eaf-453c-ad68-1f34d9617b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r4f:-form-item-description</value>
      <webElementGuid>d8201733-824a-4cd3-9bb6-0c10443a68a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>889023bf-3620-41ac-8ec7-44af06cc2c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r4f:-form-item&quot;)</value>
      <webElementGuid>2c48eae6-0ea9-4665-9413-817f0890e98f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':r4f:-form-item']</value>
      <webElementGuid>31555700-ce97-4027-b20d-918f522fce00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1e:']/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>4ca51853-4ef8-4e59-a405-7a055a069bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ceedfc5f-5501-4510-b66a-b47f3e638d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Subject name in arabic' and @name = 'nameAR' and @id = ':r4f:-form-item']</value>
      <webElementGuid>eb537413-2d59-4f0c-9b0d-635f104ecae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
