<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No data found</name>
   <tag></tag>
   <elementGuidId>b7767e3c-8f36-42b5-82c6-1b39e31128de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'No data found')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-xl.font-semibold.mt-2.mb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4d83f9b5-1865-4048-9317-7048c32a481f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl font-semibold mt-2 mb-5</value>
      <webElementGuid>3350c74f-44fa-4f9f-bb7c-04d4e2fb7a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>core.no.data.found</value>
      <webElementGuid>2bc69c73-5c65-4e3c-b04a-29486b9d27df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;w-full&quot;]/div[@class=&quot;rounded-sm overflow-auto border relative w-full&quot;]/div[@class=&quot;relative w-full overflow-auto&quot;]/table[@class=&quot;w-full table-auto caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0 bg-background&quot;]/tr[@class=&quot;w-full border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted&quot;]/td[@class=&quot;py-1 px-4 align-middle [&amp;:has([role=checkbox])]:pe-0 h-24 text-center&quot;]/div[@class=&quot;flex flex-col w-1/2 mx-auto h-96 items-center justify-center&quot;]/p[@class=&quot;text-xl font-semibold mt-2 mb-5&quot;]</value>
      <webElementGuid>eddb1c0a-4b43-4f71-ad6d-7667edd69357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[3]/div/div/table/tbody/tr/td/div/p</value>
      <webElementGuid>57ef5501-3110-434e-8ce6-89a5cfd2513b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[1]/following::p[1]</value>
      <webElementGuid>21b02b7f-de3c-4540-a733-42cfbef2eebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/following::p[1]</value>
      <webElementGuid>25a7d31b-7a59-4b32-a74e-62d2f739bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='core.create.new Subjects'])[1]/preceding::p[1]</value>
      <webElementGuid>df99883a-303d-4a36-af7b-5a0ce064baab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='core.no.data.found']/parent::*</value>
      <webElementGuid>ba514ae2-a91a-44a9-b5c4-28428009696c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d8bd4945-ffa4-44d2-9603-9c8075072c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'core.no.data.found' or . = 'core.no.data.found')]</value>
      <webElementGuid>d54c3990-fc21-4938-8525-abb7d88c8cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
