<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>program.required</name>
   <tag></tag>
   <elementGuidId>c8d0db91-3183-4ff8-8e98-4a3888a051c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Program is required')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a2a1afa6-658f-4116-ae97-bcb6de74edf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2e:-form-item-message</value>
      <webElementGuid>35df1a25-5b32-49f1-8b2a-be75fcd77122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium text-destructive</value>
      <webElementGuid>e00ff435-8246-4561-aece-a5c963e44c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>core.program.required</value>
      <webElementGuid>44fd3c9f-add3-46af-afc1-8fa5f31306a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2e:-form-item-message&quot;)</value>
      <webElementGuid>0bc714e5-1b8f-4a7d-af7e-adde697b465b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r2e:-form-item-message']</value>
      <webElementGuid>8489dd2f-20e7-43ae-b3cf-ebf9a897385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1e:']/div[2]/form/div/div[3]/p</value>
      <webElementGuid>5ece8eac-7579-4426-b125-876beabf13bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search in Programs...'])[1]/following::p[1]</value>
      <webElementGuid>dbe5d534-c1d6-4f53-ac06-81e65667b6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/following::p[1]</value>
      <webElementGuid>c7257f43-02b6-4c52-8a4d-665b001e9cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Icon (optional)'])[1]/preceding::p[1]</value>
      <webElementGuid>7e9fef7d-fdc8-4c49-8a95-25e05c34ccbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to upload'])[1]/preceding::p[1]</value>
      <webElementGuid>23a8c9a4-97dc-4a79-b1cf-5392f56aae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='core.program.required']/parent::*</value>
      <webElementGuid>0269727b-6a93-4840-bc97-a788f3b07c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>c8d8b1a0-e899-46ac-976d-0f6f4c8c363f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r2e:-form-item-message' and (text() = 'core.program.required' or . = 'core.program.required')]</value>
      <webElementGuid>e7633650-4d74-465b-a914-d0c5b68351ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
