<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>String must contain at least 2 character(s)</name>
   <tag></tag>
   <elementGuidId>9feb29db-7c5d-45d8-8427-30b8c0cd7e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'String must contain at least 2 character(s)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>451555d7-d166-40be-a922-be0bd0111e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r64:-form-item-message</value>
      <webElementGuid>a49a762a-84f2-4a3d-9ae6-72e36a9adee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium text-destructive</value>
      <webElementGuid>24a9a06d-f397-42ab-91ec-ff2b1b9b4e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>String must contain at least 2 character(s)</value>
      <webElementGuid>9aafaa71-7ccf-4f8f-9c34-a34246b0fb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r64:-form-item-message&quot;)</value>
      <webElementGuid>1b176c80-b510-4a73-b452-51f6e25e3d63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r64:-form-item-message']</value>
      <webElementGuid>392a590f-dc13-4cfe-95df-8dfd86df468e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r61:']/div[2]/form/div/div/p</value>
      <webElementGuid>d4b1404a-c9c8-41f9-a60f-438a21245807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arabic Name'])[1]/following::p[1]</value>
      <webElementGuid>ff4e8420-9131-41c7-aacd-e05dbaad4937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Subject'])[1]/following::p[1]</value>
      <webElementGuid>8f951d6b-fd79-4133-9002-19f64125f86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English Name'])[1]/preceding::p[1]</value>
      <webElementGuid>e7f1fed0-2aa8-4bba-94d7-0813351f29dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/preceding::p[1]</value>
      <webElementGuid>cd341034-aadf-4828-a3aa-d72fa823555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='String must contain at least 2 character(s)']/parent::*</value>
      <webElementGuid>2e98541d-c814-446a-9642-ad2414c1850a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/p</value>
      <webElementGuid>f3585805-22d3-4442-9a41-92c028e14286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r64:-form-item-message' and (text() = 'String must contain at least 2 character(s)' or . = 'String must contain at least 2 character(s)')]</value>
      <webElementGuid>52e6d3ba-f4c4-4912-9a98-be8598172749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
