<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Arabic</name>
   <tag></tag>
   <elementGuidId>daa97997-308c-40f4-b6ba-7357385635d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'name.ar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7eb3eb47-193b-4a36-bffd-66b72c4f41a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary-50 flex h-10 w-full rounded-md border bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring hover:bg-primary-20/20 transition-colors focus-within:bg-primary-20/20 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 peer-invalid:ring-red-600</value>
      <webElementGuid>779ab477-f8e7-462f-8af0-636016db9941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bloom name in Arabic</value>
      <webElementGuid>8f0bd03c-9191-4a77-ad4d-182a6ff9c3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name.ar</value>
      <webElementGuid>9fb50aa9-3871-49b0-b054-a1903fb68605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1i:-form-item</value>
      <webElementGuid>aaa9201b-85c3-4927-be9b-fe0806063cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1i:-form-item-description</value>
      <webElementGuid>986c52ac-1f3a-430f-8c26-1702d5adb913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad9b0771-bc56-431b-a80f-37ad6f8ec67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1i:-form-item&quot;)</value>
      <webElementGuid>c12d7bfd-709d-4a48-8334-85c37a216fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':r1i:-form-item']</value>
      <webElementGuid>7fec86c1-c514-44d8-8b49-d657877cd06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1e:']/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>5563971c-2e88-4f93-b700-57da4e3a2197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>348cefd9-c73d-43e2-8df1-8441ec08a5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Bloom name in Arabic' and @name = 'name.ar' and @id = ':r1i:-form-item']</value>
      <webElementGuid>e8195175-a67c-4740-9fef-0ab519e346e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
