<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Grouping</name>
   <tag></tag>
   <elementGuidId>2350f044-cc22-472b-b934-d7da67da398a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'grouping_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3be6ad66-54f4-42bb-ba37-ff517106b1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary-50 flex h-10 w-full rounded-md border bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring hover:bg-primary-20/20 transition-colors focus-within:bg-primary-20/20 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 peer-invalid:ring-red-600</value>
      <webElementGuid>91497262-7421-48ed-95a3-10bb8d797fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grouping_id</value>
      <webElementGuid>7b00f7dc-e153-466a-b5c3-4b3544a95636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r3l:-form-item</value>
      <webElementGuid>28ec1f23-f340-4dfc-847f-aba19b5c945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r3l:-form-item-description</value>
      <webElementGuid>9859d084-0430-4b1c-9633-9cb4ace3eb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f46a5485-8e48-4994-a04b-c54f0cd95dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>49ddf60e-d616-4fdb-8c96-318c0dbe62e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r3l:-form-item&quot;)</value>
      <webElementGuid>57fd81e9-37e7-407e-a243-43771eb6ac32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':r3l:-form-item']</value>
      <webElementGuid>8f40b5fa-f45a-4703-be17-bbd438d7cf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2i:']/div[2]/form/div/div[9]/div/input</value>
      <webElementGuid>e71ee6bb-5829-4471-a953-dadaf6c02348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>9cb39b0b-488f-4f17-95d0-c47ca79f56eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'grouping_id' and @id = ':r3l:-form-item']</value>
      <webElementGuid>7f9bb9ac-9218-4391-bf24-efaeead27ee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
