<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecondBulkSelect</name>
   <tag></tag>
   <elementGuidId>79d1676c-bb6a-4eea-b079-8a73b3ace751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='on'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de6ae187-a34a-4fc0-b675-c6c3cc0fabb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73a6c4c1-6ae1-4fad-9a69-84138f2b7500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7d955ee-c867-430b-9580-0c4e5cef0c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dde44d59-1da6-4307-826e-7d7751b97355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>5364ad48-c859-409c-8da1-eeed2289c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>784f8726-f20b-45e2-883f-903172276948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground</value>
      <webElementGuid>e5fcb227-69a5-46fd-b1d5-5892aaaae44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/button[@class=&quot;sticky&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;rounded-sm overflow-auto border bg-background relative w-full&quot;]/div[@class=&quot;relative w-full overflow-auto&quot;]/table[@class=&quot;w-full table-auto caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0 bg-background&quot;]/tr[@class=&quot;w-full border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted bg-muted&quot;]/td[@class=&quot;py-1 px-4 align-middle [&amp;:has([role=checkbox])]:pe-0 w-5&quot;]/button[@class=&quot;peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground&quot;]</value>
      <webElementGuid>76a77606-9368-4645-93eb-001a2f935bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='on'])[5]</value>
      <webElementGuid>c8ad2c1e-f869-49c3-a206-2da988a6701c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/button/div/div/div/table/tbody/tr[4]/td/button</value>
      <webElementGuid>43b5732d-cc73-48fe-809a-e0f3856ff66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdy'])[1]/following::button[2]</value>
      <webElementGuid>b25e47c6-a40c-4849-a558-0f90fc0cdfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdyw'])[1]/following::button[4]</value>
      <webElementGuid>5f669b10-0a61-4584-9d6a-57e9353f9ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/button</value>
      <webElementGuid>6eaef474-f281-4ae7-af70-0ec3f967eca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>571beb59-ef5f-4922-8fe2-1a732452602a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
