<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GradinPersentage_Islamic</name>
   <tag></tag>
   <elementGuidId>a5a09e1f-1e9e-49d1-a314-edca124999be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Course Point (0 - 100%)'])[1]/following::span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0de34371-34b7-40fb-8507-6cef03924a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>c55dbb91-38b1-44b8-80b0-f19a59f7c949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98200487-de43-4ea1-9170-305ae9542cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>01c735a6-a3ad-4558-a32a-71c277dc557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>7c60a034-6bba-4a91-85c7-c93e1bc0917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>856f4b2c-4011-4d2d-b835-6ae58872c1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9527f7f2-7b44-43e2-bb9e-a32d17be98a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative block h-4 w-4 rounded-full border border-primary/50 bg-background shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50</value>
      <webElementGuid>34482fe3-ab37-42b9-b7d7-8c5b9158d334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07bdaa83-76f8-423e-8199-adc6f0d9d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33a5280a-2ca7-4bf1-8750-cfede1c8cdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r7b:-form-item&quot;)/span[2]/span[@class=&quot;relative block h-4 w-4 rounded-full border border-primary/50 bg-background shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50&quot;]</value>
      <webElementGuid>e848ec66-6708-4ec3-9582-5fe587c83dc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id=':r7b:-form-item']/span[2]/span</value>
      <webElementGuid>bc7bbe95-7940-49b6-9338-08743ac5615f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Course Point (0 - 100%)'])[1]/following::span[5]</value>
      <webElementGuid>985267fd-1281-46e9-92de-68cecb24aa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Description (EN)'])[2]/following::span[5]</value>
      <webElementGuid>7588b25d-5feb-4072-b367-bb409fd039bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='core.grouping.select'])[1]/preceding::span[2]</value>
      <webElementGuid>134d110e-1a44-46f1-97b3-e4f3998a0542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Year'])[1]/preceding::span[3]</value>
      <webElementGuid>05aea9e5-c645-4f3c-8aa2-edefda77b741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>762d31c2-5b9e-4371-8567-66fa032a8c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0' or . = '0')]</value>
      <webElementGuid>aae7526f-0c2e-4c27-a1eb-8b49efa9d493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
