<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Islamic_FillTheInformation</name>
   <tag></tag>
   <elementGuidId>42ae5601-5ff0-4836-9b05-91ba68d5a8f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/h3/button/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a297037e-070e-4dd3-9d19-6b25d90afd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-start</value>
      <webElementGuid>780bf27e-9c04-4d72-a747-0df58007af69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Islamic</value>
      <webElementGuid>35a6a703-bf66-413c-8509-f2e75de1ddfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r6c:&quot;)/div[@class=&quot;flex items-center gap-2 flex-1&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;flex items-start&quot;]</value>
      <webElementGuid>ee1d787c-6896-423e-bbb8-2fcef7c8b8ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-:r6c:']/div/div/div</value>
      <webElementGuid>5183b93f-2a85-4011-9770-bb68b4982684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Math'])[2]/following::div[6]</value>
      <webElementGuid>534a16ec-216d-42c8-ac38-13af1739113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Islamic'])[1]/following::div[13]</value>
      <webElementGuid>79052df3-2d9f-48ba-8b48-4237d4fc7bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish'])[1]/preceding::div[2]</value>
      <webElementGuid>80b9c122-f2ec-4cb3-8101-d66db1bf420c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/button/div/div/div</value>
      <webElementGuid>29c84534-a337-4b30-9062-67a4081b7725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Islamic' or . = 'Islamic')]</value>
      <webElementGuid>c69b8d68-1b71-4a03-acfb-4123ff691515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
