<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BulkSelect1</name>
   <tag></tag>
   <elementGuidId>00bb6bc4-1441-4ab6-99a4-430e23410d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='on'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1f0a18f-a8fc-4c94-acc8-2bedc4ca411b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14fd0c19-ed31-4df2-9e9e-47fb05328e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb1f3bec-5084-4fa7-bf51-7aaf28e4c8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a2abeac-4c2a-4944-b515-50b8e98d3d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>86fa2aea-84d7-42b2-a2e6-6fa65557d365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>99365df8-ba9b-466a-be0b-c819c4675552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground</value>
      <webElementGuid>90e65085-873d-4bd5-bd6c-245ecd597370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/button[@class=&quot;sticky&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;rounded-sm overflow-auto border bg-background relative w-full&quot;]/div[@class=&quot;relative w-full overflow-auto&quot;]/table[@class=&quot;w-full table-auto caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0 bg-background&quot;]/tr[@class=&quot;w-full border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted bg-white&quot;]/td[@class=&quot;py-1 px-4 align-middle [&amp;:has([role=checkbox])]:pe-0 w-5&quot;]/button[@class=&quot;peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground&quot;]</value>
      <webElementGuid>96b52878-e163-4793-b444-a0f220d98c7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='on'])[5]</value>
      <webElementGuid>61484de7-853c-4a50-b204-a728b3ac423c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/button/div/div/div/table/tbody/tr[4]/td/button</value>
      <webElementGuid>2666755b-0f1f-40c9-9c5f-8147ead463d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/button</value>
      <webElementGuid>c530ef1b-3bb8-485d-8dcd-1535b58cd5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>b1dd1145-d811-46e0-a7d5-71088252e336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
