<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Program Type is Required</name>
   <tag></tag>
   <elementGuidId>21501ad1-3170-488e-9a14-19d9f6637630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Program Type is required' or . = 'Program Type is required')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bf4558f7-13b3-48d8-b6e6-38b48b8774ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r3f:-form-item-message</value>
      <webElementGuid>e30e0ef2-f340-4244-88ab-07ea7c9b79f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium text-destructive</value>
      <webElementGuid>1e051195-5046-4bd4-b6aa-2db1420f0cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>core.program.type.is.required</value>
      <webElementGuid>9e5378fe-6ee5-423b-bed2-10d8c6d2cbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r3f:-form-item-message&quot;)</value>
      <webElementGuid>c3e79fac-c547-4147-aa0d-1f9e1cd6b9bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r3f:-form-item-message']</value>
      <webElementGuid>9e3b3e58-acd4-44e8-9c30-07b42ba20071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1e:']/div[2]/form/div/div[3]/p</value>
      <webElementGuid>3aeaa553-4638-47ee-9e5b-e6d48c74c3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Program Type...'])[1]/following::p[1]</value>
      <webElementGuid>9a11f8c6-837c-4bf4-959c-75cdc79bedfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Type'])[2]/following::p[1]</value>
      <webElementGuid>c88de01f-2a4c-4bbe-af63-661d49f6c1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Parent (Optional)'])[1]/preceding::p[1]</value>
      <webElementGuid>621406ae-bdc4-4f9a-9556-bc02dd3102e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search in Programs...'])[1]/preceding::p[1]</value>
      <webElementGuid>021428dd-e951-40ae-8150-aee4f5648c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='core.program.type.is.required']/parent::*</value>
      <webElementGuid>f267d048-a130-4ce6-8445-3e9a00aab27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>76c3a954-d056-4cb4-a555-199ed876d348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r3f:-form-item-message' and (text() = 'core.program.type.is.required' or . = 'core.program.type.is.required')]</value>
      <webElementGuid>6ae0f454-25e3-49c9-a4cf-4ac947ffa4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
