<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select The Section</name>
   <tag></tag>
   <elementGuidId>1467bc28-907a-4f31-9be5-8d1324eddfc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='on'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65d3674e-75b0-4810-b499-60f2cf8f7bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17105aa1-b74e-4fc3-9628-798062e06b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>78661237-5a74-4267-b74c-d3981c8607f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39bbd5ef-20ab-48dc-aeb3-17ab565ecec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>60e544c5-e87f-435a-b983-1366bb03cebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e0e1af25-0385-4ea5-8ca7-2549de465e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground w-4 h-4 items-center flex justify-center</value>
      <webElementGuid>8a506106-1414-45da-9cdb-f14b34e0c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r4n:&quot;)/div[@class=&quot;pb-4 pt-0 flex m-2 gap-x-6&quot;]/div[@class=&quot;bg-white rounded-3xl p-5 mt-9 me-6 w-full max-w-[45%] overflow-x-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;flex flex-col gap-2 overflow-auto max-h-52&quot;]/div[3]/div[@class=&quot;ps-6 flex flex-col gap-2 py-2&quot;]/div[2]/div[@class=&quot;ps-6 flex flex-col gap-2 py-2&quot;]/div[2]/div[@class=&quot;ps-6 flex flex-col gap-2 py-2&quot;]/div[1]/div[@class=&quot;flex items-start gap-1&quot;]/label[@class=&quot;text-secondary-50 text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 flex items-center gap-1&quot;]/button[@class=&quot;peer size-4 shrink-0 rounded border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:border-primary data-[state=checked]:text-primary-foreground w-4 h-4 items-center flex justify-center&quot;]</value>
      <webElementGuid>abfb8aaa-e64f-4635-a00e-f6378b257e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='on'])[8]</value>
      <webElementGuid>1f3e8f14-5ffa-4c0b-b6a3-35350905637c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r4n:']/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/label/button</value>
      <webElementGuid>d0038fc0-a815-4cd0-a46a-359f4b696476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/label/button</value>
      <webElementGuid>273fe87f-e724-4366-bc7b-199a09b8a4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>0003dac6-165b-4c3d-a840-2bf58782c90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
