<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click On Course Subject</name>
   <tag></tag>
   <elementGuidId>7500c0fc-aca1-4a58-b4f7-949cf3d19404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88433d75-b677-4eab-bc5f-660a62484cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-primary-20/20 stepper__step-button-container p-0 pointer-events-none w-[var(--step-icon-size)] h-[var(--step-icon-size)] border-2 flex rounded-full justify-center items-center data-[clickable=true]:pointer-events-auto data-[current=true]:border-background data-[current=true]:bg-primary data-[current=true]:text-white bg-primary border-primary text-primary-foreground</value>
      <webElementGuid>a5506fe0-7840-4939-9a69-bfe798a881a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a691ecc-0494-4d83-9bae-a38c3949a668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7998397d-0ef4-48ce-99db-9ace81c95636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edcae135-496e-470d-a258-0e58781d8597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88f1e9ec-7aa7-45ae-aaea-9234af0d2b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>667ec6d3-a2e8-44d9-b54d-eead591262a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-clickable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86c2809a-db7f-4976-bc34-21437189b91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>684eb399-ffe3-48d5-9931-1933a4af76f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>step</value>
      <webElementGuid>ddfeca7f-5da5-41c5-bbee-932f185ee88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>02e09af6-a8f1-4743-ae40-fbf671845dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;flex w-full flex-col gap-4&quot;]/div[@class=&quot;stepper__main-container flex w-full flex-wrap justify-between flex-row&quot;]/div[@class=&quot;stepper__horizontal-step flex items-center relative transition-all duration-200 [&amp;:not(:last-child)]:flex-1 [&amp;:not(:last-child)]:after:transition-all [&amp;:not(:last-child)]:after:duration-200 [&amp;:not(:last-child)]:after:content-[''] [&amp;:not(:last-child)]:after:h-[2px] [&amp;:not(:last-child)]:after:bg-border data-[completed=true]:[&amp;:not(:last-child)]:after:bg-primary data-[invalid=true]:[&amp;:not(:last-child)]:after:bg-destructive [&amp;:not(:last-child)]:after:flex-1 [&amp;:not(:last-child)]:after:ms-[var(--step-gap)] [&amp;:not(:last-child)]:after:me-[var(--step-gap)]&quot;]/div[@class=&quot;stepper__horizontal-step-container flex items-center&quot;]/button[@class=&quot;whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-primary-20/20 stepper__step-button-container p-0 pointer-events-none w-[var(--step-icon-size)] h-[var(--step-icon-size)] border-2 flex rounded-full justify-center items-center data-[clickable=true]:pointer-events-auto data-[current=true]:border-background data-[current=true]:bg-primary data-[current=true]:text-white bg-primary border-primary text-primary-foreground&quot;]</value>
      <webElementGuid>96b2d74d-d46e-4d0d-b742-2d0d2ba2d28c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>dae8128a-7728-41b0-ade1-16a730e145ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div[2]/div/button</value>
      <webElementGuid>70875958-7e7c-4158-8627-8be32069f20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Settings'])[1]/following::button[1]</value>
      <webElementGuid>6064509e-62be-4577-a9e1-af0319a3016e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Courses'])[3]/following::button[2]</value>
      <webElementGuid>bfbf8965-c0eb-41fa-aba1-eed85dda94ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Subject'])[1]/preceding::button[1]</value>
      <webElementGuid>ef3a2fd9-bc85-406d-9634-54a4459cd73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add as much Subjects as you want'])[1]/preceding::button[1]</value>
      <webElementGuid>7f00551b-1c36-42c6-80a5-e3782718cbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button</value>
      <webElementGuid>856af39f-f1ee-4077-bb50-37c6b27629df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '2' or . = '2')]</value>
      <webElementGuid>9aacb8ce-87c4-41c1-9fd2-6934cedf6da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
